Feature display chart
kuri-team/rmit-cosc2081-assignment pull request #9
Opened 2021-08-12 04:28 UTC by rider3458

Implement display-chart
Move codes for querying and groups' range to separate methods

2021-08-12 13:38 UTC, miketvo requested changes
- Data points need to be spaced out evenly across the x-axis.
- Incorrect y positions

2021-08-13 02:57 UTC, rider3458 commented
currently there is only 1 chart and it cannot handle more than 79 groups due to the its maximum number of columns

2021-08-13 16:20 UTC, miketvo approved these changes
I will ask Dr. Tri about Issue #11 and give you a direction to further implement this feature in the next sprint

2021-08-14 03:53 UTC, doanyennhi approved these changes

2021-08-14 04:32 UTC, merged